name: lab_2_mis
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2 # https://pub.dev/packages/firebase_core
  firebase_auth: ^5.3.4 # https://pub.dev/packages/firebase_auth
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7
  firebase_app_check: ^0.3.0+4
  cloud_firestore: ^5.0.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  http: ^1.5.0

  cupertino_icons: ^1.0.8
  firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
